# NumPy Tutorial

Comparing the performance difference between numpy and Python list

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 55.4 ms
Wall time: 2.01 s


# # The NumPy ndarray: A Multidimensional Array Object

In [2]:
#Generating an array of random numbers with 2 rows and 3 columns
data = np.random.randn(2,3)
data

array([[-1.60929915,  0.5736899 , -0.52019218],
       [ 0.97714836, -0.69930996, -1.76383933]])

In [3]:
data*3

array([[-4.82789746,  1.72106971, -1.56057655],
       [ 2.93144508, -2.09792988, -5.29151799]])

In [4]:
data + data

array([[-3.21859831,  1.14737981, -1.04038437],
       [ 1.95429672, -1.39861992, -3.52767866]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

# # Creating ndarrays

Creating an array from a list

In [7]:
data = [4,5,6,7,8,9]

array = np.array(data)

array

array([4, 5, 6, 7, 8, 9])

Creating an array from a list of lists

In [8]:
data = [[1,2,3],[4,5,6]]
array = np.array(data)
array

array([[1, 2, 3],
       [4, 5, 6]])

Creating an array of zeroes

In [9]:
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [10]:
array = np.zeros((5,5)) #remember to use two parentheses
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Changing data type type of an array with astype

In [11]:
data = np.array([1,2,3])
data.dtype

dtype('int32')

In [12]:
data = data.astype(np.float64)
data.dtype

dtype('float64')

In [13]:
data_string = np.array(['1','2','3'], dtype=np.string_)
data_string.dtype

dtype('S1')

In [14]:
data_numeric = data_string.astype(np.float64)
data_numeric.dtype

dtype('float64')

# # Arithmetic with NumPy Arrays

Any arithmetic operation between equal-size arrays is done element-wise

In [15]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[7,8,9],[10,11,12]])

Adding two arrays

In [16]:
array_3 = array_1 + array_2
array_3

array([[ 8, 10, 12],
       [14, 16, 18]])

Multiplying an array with a number

In [17]:
array_4 = array_1*2
array_4

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# # Indexing and slicing